### ISSUE TITLE
代码格式问题(happyLify/buyCoin/index.js)@adtxgc

### ISSUE THREAD

**Issue by lingxiFront** [lingxiFront/CodeReview#4]
@adtxgc  **63**行方法注释有问题
[https://github.com/lingxiFront/CodeReview/blob/master/happyLify/buyCoin/index.js](https://github.com/lingxiFront/CodeReview/blob/master/happyLify/buyCoin/index.js)

**Comment by adtxgc** [comment]
已解决 #5
